version: '3'

services:
  mypython:
  image: apple1002/my-python-app
  restart: always
  container_name: my-python-app-service
  port:
    - "5000:5000"
  volumes:
    --mount type=bind,source=$(pwd),target=/devops-challenge
  environment:
    hostname: suhanish0910.site
    hostport: "5000"
  replicas: 5

  
  
 
