---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: ansible
  tasks:
    - name: Update the packages in remote server
      yum: 
        update_only: yes
        update_cache: yes
    
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present
    
    - name: add tomcat group
      group:
       name: tomcat
    
    - name: add tomcat user
      user:
        name: tomcat
        group: tomcat
        home: /usr/share/tomcat
        createhome: no

    - name: create /opt/tomcat folder
      file: 
        path: /opt/tomcat
        state: directory
        mode: 0755

    - name: download & unarchive
      unarchive:
        src: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.46/bin/apache-tomcat-8.5.46.tar.gz
        dest: /opt/tomcat
        remote_src: yes

    - name: Change ownership
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy Tomcat service from local to remote
      copy:
        src: tomcat.service
        dest: /etc/systemd/system/
        mode: 0755
    
    - name: Start and enable Tomcat Service
      systemd:
          name: tomcat
          state: started
          enabled: true
          deamon_reload: true



